/*
 * This file was automatically generated by EvoSuite
 * Thu Jul 18 07:22:45 GMT 2019
 */

package com.neo.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import com.neo.controller.DockerController;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DockerController_ESTest extends DockerController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DockerController dockerController0 = new DockerController();
      String string0 = dockerController0.index();
      assertEquals("Hello Docker!", string0);
  }
}
